version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:80"
  
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - api
