version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "5000:80"
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - api
